hmcts/cpp-module-terraform-azurerm-aks-config

gatekeeper.tf, manifests/gatekeeper/constraint.yaml, manifests/gatekeeper/whitelistedimages.yaml, variables.tf
EI-904 : Content trust on docker registries
Disable deploying images from any repos other than whitelisted repos
=> Dev ei 904

velero.tf
update azure plugin version to 1.6.0 which is the latest
=> Update velero azure plugin version

istio.tf, manifests/istio/istio_authorizationpolicy.yaml, variables.tf
https://tools.hmcts.net/jira/browse/EI-1000
Updated istio authorization policy for source IP EI-967 && EI-1001
```
[ ] Yes
[x] No
```
=> Updated istio authorization policy for source IP EI-967 && EI-1001

manifests/istio/istio_authorizationpolicy.yaml
https://tools.hmcts.net/jira/browse/EI-1000
Updated Authorization policy to allow EI-1000
```
[ ] Yes
[x] No
```
=> Updated Authorization policy to allow EI-1000

pgadmin.tf
pgadmin version
```
[ ] Yes
[ ] No
```
=> pgadmin version

prometheus.tf
https://tools.hmcts.net/jira/browse/EI-985
Updated the backup label dEI-985
```
[ ] Yes
[x] No
```
=> Updated the backup label dEI-985

prometheus.tf
https://tools.hmcts.net/jira/browse/EI-985
Updated the backup label EI-985
```
[ ] Yes
[ ] No
```
=> Updated the backup label EI-985

pgadmin.tf
https://github.com/hmcts/cpp-module-terraform-azurerm-aks-config/pull/new/dev/ei-935-3
```
[ ] Yes
[ ] No
```
=> pgadmin source image

pgadmin.tf
=> fix pgadmin Image issue

dynatrace.tf
=> dynatrace secret creation

istio.tf
=> make istio switch conditional like annotation

chart-values/prometheus.tmpl, prometheus.tf
https://tools.hmcts.net/jira/browse/EI-1134
Disable node exporter and scrape additional configs
```
[ ] Yes
[X] No
```
=> Remove prometheus node-exporter

chart-values/prometheus.tmpl
https://tools.hmcts.net/jira/browse/EI-1134
Scrape config update
```
[ ] Yes
[ ] No
```
=> Updated additional scrape config

chart-values/prometheus.tmpl
https://tools.hmcts.net/jira/browse/EI-1134
```
[ ] Yes
[ ] No
```
=> Disable kubelet and scrape one metrics

chart-values/prometheus.tmpl
https://tools.hmcts.net/jira/browse/EI-1134
```
[ ] Yes
[ ] No
```
=> Kubelet disable

prometheus.tf
https://tools.hmcts.net/jira/browse/EI-1174
```
[ ] Yes
[ ] No
```
=> Grafana redirect update

data.tf, variables.tf
=> use variable for resource group

cert-manager.tf, data.tf, istio.tf, manifests/cert-manager/cert-issuer.yaml, manifests/istio/istio_ingress_gateway.yaml, outputs.tf, variables.tf
https://tools.hmcts.net/jira/browse/EI-1184
Adds a new Istio gateway for the web tier
```
[ ] Yes
[ ] No
```
=> feat: add web istio gateway

cert-manager.tf, data.tf, istio.tf, manifests/cert-manager/cert-issuer.yaml, manifests/istio/istio_ingress_gateway.yaml, outputs.tf, variables.tf
Reverts hmcts/cpp-module-terraform-azurerm-aks-config#42
=> Revert "feat: add web istio gateway"

data.tf, istio.tf, outputs.tf
Corrects istio gateway name for web
```
[ ] Yes
[ ] No
```
=> fix: correct web istio gateway name

cert-manager.tf, data.tf, manifests/cert-manager/cert-issuer.yaml, manifests/istio/istio_ingress_gateway.yaml, outputs.tf, variables.tf
https://tools.hmcts.net/jira/browse/EI-1184
Adds a new istio web gateway
```
[ ] Yes
[ ] No
```
=> Ei 1184/istio 3

data.tf, outputs.tf
[EI-1184](https://tools.hmcts.net/jira/browse/EI-1184)
Exports istio gateway web ip address so we can create an A record in DNS
```
[ ] Yes
[ ] No
```
=> chore: add istio web gateway output

main.tf
https://tools.hmcts.net/jira/browse/EI-1261
Updated index to foreach
```
[ ] Yes
[ ] No
```
=> Update index in for_each to numeric

main.tf, manifests/common/networkpolicy.yaml
https://tools.hmcts.net/jira/browse/EI-1261
Updated istio-system namespace for network policy that is applied to prometheus
```
[ ] Yes
[ ] No
```
=> Update istio-system ns for prom

sonarqube.tf, variables.tf
https://tools.hmcts.net/jira/browse/EI-1205?focusedId=1652935
```
[ ] Yes
[ ] No
```
=> Dev ei 1205 sonar multiple hosts

azure-pipelines.yaml, kiali.tf, pgadmin.tf, sonarqube.tf
add dependency to gatekeeper for pgadmin,sonarqube, kiali
```
[ ] Yes
[ ] No
```
=> add dependency to gatekeeper

smashing.tf, variables.tf
https://tools.hmcts.net/jira/browse/EI-1359
Deploy smashing as cluster wide service
=> EI-1359 Added smashing at cluster level

aks_rbac.tf, outputs.tf, variables.tf
https://tools.hmcts.net/jira/browse/EI-1413
Adds support to create azure key vault secret for the AKS cluster kubeconfig.
=> feat: create aks rbac akv secrets

versions.tf
N/A
Removes deprecated template provider which doesn't work with M1 chips and was replaced with the templatefile function
=> chore: remove deprecated template provider

jenkins.tf
https://tools.hmcts.net/jira/browse/EI-1599
bind jenkins-deploy to default service account on jenkins namespace
=> update jenkins dafault permission

ado-agents.tf, chart-values/aks-rbac.yaml
https://tools.hmcts.net/jira/browse/EI-1380
adding ado-agent to admin
=> fix for ADO

prometheus.tf
https://tools.hmcts.net/jira/browse/EI-1717
Remove promtheus backup label
=> Remove promtheus backup label

prometheus.tf
https://tools.hmcts.net/jira/browse/EI-1717
Remove label for prometheus backup
=> Remove label for prometheus backup

velero.tf
https://tools.hmcts.net/jira/browse/EI-1705
Upgrade velero
=> Velero update

velero.tf
https://tools.hmcts.net/jira/browse/EI-1705
Fix velero snapshot provider value
=> Fix velero snapshot provider value

istio.tf
https://tools.hmcts.net/jira/browse/EI-1769
Update spec for istio-ingress
=> Update spec for istio-ingress

ado-agents.tf, variables.tf
https://tools.hmcts.net/jira/browse/EI-1720
Injects istio sidecar to ado agents (optional)
=> chore: add annotation var to ado agents

ado-agents.tf, istio.tf, jenkins.tf, manifests/istio/istio_peerauthentication.yaml, variables.tf
https://tools.hmcts.net/jira/browse/EI-1749
Parameterise ISTIO peer auth mode.
Disable istio injection for Jenkins and ADO namespace
=> EI-1749 Disable istio mtls on Jenkins and ADO namespaces

jenkins.tf
[EI-1792](https://tools.hmcts.net/jira/browse/EI-1792)
Removing istio injection explicit disable
=> chore: removing istio injection disablement

download_charts.tf
https://tools.hmcts.net/jira/browse/EI-1790
=> Parameterise aks-config module [EI-1790]

variables.tf
Reverts hmcts/cpp-module-terraform-azurerm-aks-config#102
=> Revert "Increase resource limits for smashing"

chart-values/prometheus-adapter.tmpl, prometheus.tf
https://tools.hmcts.net/jira/browse/EI-1850
=> Push istio_request_per_second metric [EI-1850]

manifests/cert-manager/cert-manager.yaml
https://tools.hmcts.net/jira/browse/EI-1923
update webhook validate timeout for cert manager
=> update cert manager timeout

alerts.tf, variables.tf
https://tools.hmcts.net/jira/browse/EI-1924
=> Add system alerts [EI-1924]

.terraform.lock.hcl, manifests/istio/crds/1.22.3/crd-all.gen.yaml, velero.tf, versions.tf
See [EI-2154](https://tools.hmcts.net/jira/browse/EI-2154)
Bump velero helm chart
=> chore: bump velero image

azure_service_operator.tf
https://tools.hmcts.net/jira/browse/EI-2152
Moved the default values in aks-config
=> Updated the tolerations and nodeaffinity for aso operator

alerts.tf
https://tools.hmcts.net/jira/browse/EI-2148
Alert rule creation failing due to possible updates/removal on MS side
Tested apply on PRP
=> EI-2148 Fix aks_node_count_not_in_ready_state alert

manifests/dynatrace/dynatrace.com_dynakubes.yaml
https://tools.hmcts.net/jira/browse/EI-2273
Updated priority class for dynatrace
=> Updated priority class for dynatrace

chart-values/prometheus.tmpl, prometheus.tf, variables.tf
https://tools.hmcts.net/jira/browse/DTSPO-22456
add persistence support and give editor access by default
=> Dtspo 22456

chart-values/prometheus.tmpl
=> add grafana storage support

chart-values/prometheus.tmpl
https://tools.hmcts.net/jira/browse/DTSPO-22307
scrape application prometheus metrics
=> add pronetheus config for scraping app metrics

sonarqube.tf
parameterize sonarqube init container images
=> parameterize sonarqube init container images

ado-agents.tf
https://tools.hmcts.net/jira/browse/DTSPO-24552
Create default sidecar config for egress to limit the routes exposed to ado-agent namespace
Tested on validation pipelines
=> Fix sidecar OOM for ado agent when isito is enabled

ado-agents.tf
https://tools.hmcts.net/jira/browse/DTSPO-24552
Fix LANG issues for validation due to missing env variables
https://dev.azure.com/hmcts-cpp/cpp-apps/_build/results?buildId=84013&view=logs&j=32f9e290-27d7-5525-915d-e78f83620294&t=e3e3301d-5ccc-516c-0387-a4ad9ded0e0f
=> DTSPO-24552 Add LANG variables to ado-agent scaledjob

download_charts.tf
https://tools.hmcts.net/jira/browse/DTSPO-19725
update helm version
=> update helm version

ado-agents.tf, manifests/ado-agents/ado_agents.yaml.tpl, variables.tf
https://tools.hmcts.net/jira/browse/DTSPO-26449
parameterize nonroot for ado agent
=> 26449 test

ado-agents.tf
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
Remove ccm-namespace label for ado
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
=> Remove ccm-namespace label for ado
